### PR TITLE
[REVIEW] Reverting change that removed `unsigned` in dispatch_spmv_orig.cuh

### LINKED ISSUE #161: warning in cub/device/dispatch/dispatch_spmv_orig.cuh
Related to: https://github.com/NVlabs/cub/issues/55

in cub/device/dispatch/dispatch_spmv_orig.cuh line 666 - 674
```cpp
            dim3 spmv_grid_size(
                CUB_MIN(num_merge_tiles, max_dim_x),
                (num_merge_tiles + max_dim_x - 1) / max_dim_x,
                1);

            dim3 segment_fixup_grid_size(
                CUB_MIN(num_segment_fixup_tiles, max_dim_x),
                (num_segment_fixup_tiles + max_dim_x - 1) / max_dim_x,
1);
```

This generates the following warning as num_merge_tiles and num_segment_fixup_tiles are unsigned int and max_dim_x is int. This may be harmless but better be fixed...

```
/home/seunghwak/RAPIDS/cugraph/cpp/build/gunrock/externals/cub/cub/device/dispatch/dispatch_spmv_orig.cuh:666:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             dim3 spmv_grid_size(
                     ~~~~~~~~~~~^                 
/home/seunghwak/RAPIDS/cugraph/cpp/build/gunrock/externals/cub/cub/device/dispatch/dispatch_spmv_orig.cuh:671:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             dim3 segment_fixup_grid_size(
                              ~~~~~~~~~~~^ 
```

### LINKED ISSUE #195: Recent change in device_spmv.cuh causing incorrect results
I've been testing CUDA11 integration with a recent release (7.8.0) of Cupy and found that cub's spmv was returning incorrect results. The results almost appear as though the data is being corrupted (potentially from incorrect array indexing). https://github.com/cupy/cupy/issues/3822 contains the detailed summary of the problem.

Here's a simple example of what we're seeing. `a` is using cub's `device_spmv` and `b` is not:
```python
>>> a.T.dot(cupy.ones(a.shape[0])).reshape(1, a.shape[1])
array([[0.00000000e+000, 0.00000000e+000, 4.24399158e-314, ...,
        1.10383165e-307, 1.10512862e-307, 1.10636362e-307]])
>>> b.T.dot(cupy.ones(b.shape[0])).reshape(1, b.shape[1])
array([[3056.30047519, 3058.09608272, 3009.4495842 , ..., 1505.96878088,
        1460.47145535, 1505.26624145]])
```

The problem seems isolated to this commit: https://github.com/NVlabs/cub/commit/b2e64cf0fb4ea7ace6c86ca6765ca7c1087ef82e and when that commit is reverted, the example above returns correct results (again, `a` is using `device_spmv` and `b` is not):

```python
>>> a.T.dot(cupy.ones(a.shape[0])).reshape(1, a.shape[1])
array([[3058.34350657, 3071.2141306 , 3059.92383792, ..., 1466.52647562,
        1441.08203412, 1479.81493357]])
>>> b.T.dot(cupy.ones(b.shape[0])).reshape(1, b.shape[1])
array([[3058.34350657, 3071.2141306 , 3059.92383792, ..., 1466.52647562,
        1441.08203412, 1479.81493357]])
``` 

I'm not sure if there are any automated tests for `device_spmv.cuh` internally, but I quickly grepped the tests in this repository for `spmv` and didn't get any results.

### PR DESCRIPTION
**Pull request by cjnolet**
Closes #195 
Closes #161

### CODE REVIEW

**Comment by allisonvacanti** [comment]
Ping @cjnolet -- not sure if you saw my question above.

**Comment by allisonvacanti** [comment]
Closing for lack of response -- feel free to reopen with more information as detailed above if you still need this.

**Comment by leofang** [comment]
Hi @allisonvacanti Not sure if it could work this way: Could you reopen this PR and reassign to me so that I can take over and investigate when I have time? I can't promise a date but can put this in my queue 😁 Thanks!

**Comment by allisonvacanti** [comment]
@leofang Works for me -- thanks!

**Comment by leofang** [comment]
I am looking into this right now, so will bomb this thread later this afternoon. Looks like as of CUDA 11.2.0 the bug still exists, but is gone on the current master. Trying to figure out what fixed it...

**Comment by leofang** [comment]
For some reason `git bisect` complains about "Some good revs are not ancestors of the bad rev" when bisecting against the current master. Is it because of the earlier repo change?

**Comment by leofang** [comment]
nvm, I was being silly 😅

**Comment by leofang** [comment]
Hi @allisonvacanti I am done with my checks. As @cjnolet [pointed out](https://github.com/cupy/cupy/issues/3822#issuecomment-678017362), the first commit causing the spmv error is https://github.com/NVIDIA/cub/commit/b2e64cf0fb4ea7ace6c86ca6765ca7c1087ef82e, and it seems to be fixed by your commit https://github.com/NVIDIA/cub/commit/63e2ad4be6316c98db99b90f2d113096d6e96038 from #249 🎉 So looks like the fix will be included in CUDA 11.2.2 or CUDA 11.3, right? Please feel free to close this PR and the linked bug reports.

FYI this is how I checked locally: with each `git bisect` I rebuild CuPy's `cub` module and run the test:
```
rm cupy/cuda/cub.cp*
pip install -v -e .
python test_cub_csrmv_bug.py
```
the output script is taken from @cjnolet's test code in cupy/cupy#3822:
```python
# test_cub_csrmv_bug.py
import cupy

a = cupy.sparse.random(100, 100, format='csr', density=0.9)
cupy.core.set_routine_accelerators(['cub'])
print(a.T.dot(cupy.ones(a.shape[0])))
print(a.dot(cupy.ones(a.shape[1])))
```
The output arrays should not contain values of order `1E-314`.

**Comment by allisonvacanti** [comment]
Excellent news -- I love it when bugs accidentally fix themselves :D

Thanks for checking into this, @leofang.

**Comment by allisonvacanti** [comment]
To answer the question about releases, the cuda toolkit usually ships with a slightly old version of thrust/cub. This likely won't be included until 11.4, or possibly a 11.3.x update at the earliest. CTK 11.3 will include thrust/cub 1.11.0.

**Comment by leofang** [comment]
Great, thanks for the info @allisonvacanti. Will discuss with the team for working around the bug.

**Pull request closed without merging**
