### PR TITLE
Support reduction for more than 2^31 items

### PR DESCRIPTION
**Pull request by senior-zero**
This PR partially addresses the following [issue](https://github.com/NVIDIA/cub/issues/584). Supporting larger offsets for `ArgMin` and `ArgMax` would have to wait, since it's a bit more involving. There also could be a bit better testing, but it might wait till Catch2 rewrite. 

The main purpose of this PR is to unblock original issue by providing an example of what we expect from such a change. The main direction of this modification can be found [here](https://github.com/NVIDIA/cub/issues/212).

### CODE REVIEW

**Review by elstehle — APPROVED** [review]
LGTM

**Review by kaatish — APPROVED** [review]

**Comment by senior-zero** [comment]
Because `ChooseOffsetT` leads to unsigned offsets usage the codegen changed (14% increase in kernel size). Benchmarks show about 1% slowdown for reduction due to that. I've changed `ChooseOffsetT` to provide singed offsets instead, which leads to the same code generated. Also benchmarked radix sort, since it's affected by the change and got up to 4% speedup there.

**Comment by leofang** [comment]
Hi @senior-zero, glad to see this patch landed! Would it be backported to the 1.17.x branch?

**Comment by senior-zero** [comment]
Hello @leofang! I completely forgot to reply about backporting this PR. Sorry about that!

I wouldn't like to backport this. Is there something stopping you from using the newer version of CUB. Please let us know if we can help switch to a more recent version of CUB or fix potential issues.

**Pull request merged**
