### PR TITLE
Put in somewhat hacky fix for out of bounds accesses

### PR DESCRIPTION
**Pull request by jwyles**
This is a somewhat hacky fix for the out of bounds memory accesses noted in issue #139, hopefully this will help in finding the root cause of the issue.

### CODE REVIEW

**Comment by allisonvacanti** [comment]
Looks like this was closed accidentally during the repo move. Reopening.

**Comment by allisonvacanti** [comment]
Converting to draft to prevent merging -- without looking too closely, it looks like this is meant to provide context about #139, not necessarily resolve it.

**Review by brycelelbach — APPROVED** [review]
These don't look that hacky to me.

**Comment by allisonvacanti** [comment]
Closing -- #352 incorporates the changes from this PR, fixes some other issues, and adds testing for `DeviceSpmv`. Thanks for the contribution!

**Pull request closed without merging**
