### PR TITLE
Fix incorrect issue number in changelog

### PR DESCRIPTION
**Pull request by peetw**

### CODE REVIEW

**Comment by allisonvacanti** [comment]
Looks like this was closed accidentally during the repo move. Reopening.

The change looks correct to me. This might need some formatting changes to mesh with the current `main` branch.

**Comment by allisonvacanti** [comment]
This will need to have conflicts resolved (CHANGE_LOG.TXT has moved and been reformatted).

**Comment by peetw** [comment]
@allisonvacanti done 👍

**Comment by allisonvacanti** [comment]
Thanks! I'll get this in during the next round of integrations.

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
