### PR TITLE
Add BFloat16 support for radix sort

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Ready for review, tests pass.

**Comment by allisonvacanti** [comment]
This looks good to me. Thanks for taking the time to work on this!

Can squash the branch down to a single commit, and also change the comment about PyTorch in the test wrapper implementation? I know it's meant casually, but some internal legal folks may have an overreaction to that phrasing ;)

**Comment by zasdfgbnm** [comment]
@allisonvacanti I have squashed this PR, and changed the comment to:
```
        // Refrence:
        // https://github.com/pytorch/pytorch/blob/44cc873fba5e5ffc4d4d4eef3bd370b653ce1ce1/c10/util/BFloat16.h#L51
```

**Comment by allisonvacanti** [comment]
Thanks -- I'll start tests soon.

**Comment by allisonvacanti** [comment]
Rebased and noted bfloat16 support in the docs. My doc change will conflict with #307, but I'll resolve that when merging this.

Starting tests now.

**Comment by allisonvacanti** [comment]
gpuCI: NVIDIA/thrust#1439

DVS CL: 29986609

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
